# Generated by Django 2.2.28 on 2022-07-16 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210311_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='phone number'),
        ),
    ]
