version: '3.5'
services:

  app:
    build: .
    env_file: .env
    ports:
      - 8000:8000
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app

  postgres:
    image: postgres
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis
    env_file: .env
    ports:
      - 6379:6379
    volumes:
      - redis:/data

volumes:
  postgres:
  redis:
